---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers: 
      - name: blue-container
        image: acrcosmotal.azurecr.io/app/91116297133907383ec790837bb1c9cf4b7f818d:91116297
         ports:
          - name: http 
            containerPort: 80
      resources:
           limits:
             cpu: "0.5"
             memory: "512Mi"
           requests:
             cpu: "0.25"
             memory: "256Mi"         